[package]
edition.workspace = true
name = "modern-lstm"
version = "0.22.0-pre.2"

[lints]
workspace = true

[features]
cuda = ["cortex/cuda"]
flex = ["cortex/flex"]
tch-cpu = ["cortex/tch"]
tch-gpu = ["cortex/tch"]
wgpu = ["cortex/wgpu"]

[dependencies]
cortex = { workspace = true, features = ["default", "train"] }

# Random number generator
rand = { workspace = true, features = ["thread_rng"] }
rand_distr = { workspace = true }

# Serialization
serde = { workspace = true, features = ["std", "derive"] }

# Organise the results in dataframe
planus = { workspace = true }
polars = { workspace = true }
