[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "ROCm HIP backend for the Cortex framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "rocm", "hip"]
license.workspace = true
name = "cortex-rocm"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-rocm"
documentation = "https://docs.rs/burn-rocm"
version.workspace = true

[lints]
workspace = true

[features]
default = ["fusion", "cortex-cubecl/default", "cubecl/default"]
doc = ["cortex-cubecl/doc"]
std = ["cortex-cubecl/std", "cubecl/std"]

tracing = [
    "cubecl/tracing",
    "cortex-cubecl/tracing",
    "cortex-backend/tracing",
    "cortex-fusion?/tracing",
]

fusion = ["cortex-fusion", "cortex-cubecl/fusion"]
autotune = ["cortex-cubecl/autotune"]
autotune-checks = ["cortex-cubecl/autotune-checks"]

[dependencies]
cubecl = { workspace = true, features = ["hip"] }
cortex-cubecl = { workspace = true, features = ["default"] }
cortex-backend = { workspace = true, features = [
    "default",
    "cubecl-hip",
] }
cortex-fusion = { workspace = true, optional = true, features = ["default"] }

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
