[package]
name = "wgan"
version = "0.22.0-pre.2"
edition.workspace = true

[lints]
workspace = true

[features]
flex = ["cortex/flex"]
tch-cpu = ["cortex/tch"]
tch-gpu = ["cortex/tch"]
wgpu = ["cortex/wgpu"]
cuda = ["cortex/cuda"]

[dependencies]
cortex = { workspace = true, features=["default", "train", "vision"] }
image = { workspace = true }
