[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science", "no-std", "embedded", "wasm"]
description = "Neural network building blocks for the Cortex deep learning framework"
documentation = "https://docs.rs/burn-nn"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
license.workspace = true
name = "cortex-nn"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-nn"
version.workspace = true

[lints]
workspace = true

[features]
default = ["std", "cortex-core/default"]
doc = [
    "std",
    # Doc features
    "cortex-core/doc",
]
std = ["cortex-core/std", "num-traits/std"]

tracing = ["cortex-core/tracing"]

[dependencies]

# ** Please make sure all dependencies support no_std when std is disabled **
cortex-core = { workspace = true }

num-traits = { workspace = true }

[dev-dependencies]
cortex-core = { workspace = true, features = ["autodiff"] }
rstest = { workspace = true }

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
